// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZYe_pmRsZhU9_bAI_rdydAjP__yqK9DA',
    appId: '1:955511198104:web:8b70c62b7776c662f09bed',
    messagingSenderId: '955511198104',
    projectId: 'travelconnekt-458bf',
    authDomain: 'travelconnekt-458bf.firebaseapp.com',
    storageBucket: 'travelconnekt-458bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5UWjbd-BNzrcGBDfjYEfP6Qr8f7Cnge8',
    appId: '1:955511198104:android:d5d94e76bb34c5fef09bed',
    messagingSenderId: '955511198104',
    projectId: 'travelconnekt-458bf',
    storageBucket: 'travelconnekt-458bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwi8srj9XaibcJva6nt6s-szNUFKlb62M',
    appId: '1:955511198104:ios:c0dc8217e09a933cf09bed',
    messagingSenderId: '955511198104',
    projectId: 'travelconnekt-458bf',
    storageBucket: 'travelconnekt-458bf.firebasestorage.app',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwi8srj9XaibcJva6nt6s-szNUFKlb62M',
    appId: '1:955511198104:ios:c0dc8217e09a933cf09bed',
    messagingSenderId: '955511198104',
    projectId: 'travelconnekt-458bf',
    storageBucket: 'travelconnekt-458bf.firebasestorage.app',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZYe_pmRsZhU9_bAI_rdydAjP__yqK9DA',
    appId: '1:955511198104:web:3246443cefb8c40ef09bed',
    messagingSenderId: '955511198104',
    projectId: 'travelconnekt-458bf',
    authDomain: 'travelconnekt-458bf.firebaseapp.com',
    storageBucket: 'travelconnekt-458bf.firebasestorage.app',
  );

}